// default package
// Generated 1 feb 2025, 22:43:07 by Hibernate Tools 6.5.1.Final

import java.math.BigInteger;

/**
 * Contacts generated by hbm2java
 */
public class Contacts implements java.io.Serializable {

	private BigInteger contactId;
	private Customers customers;
	private String firstName;
	private String lastName;
	private String email;
	private String phone;

	public Contacts() {
	}

	public Contacts(BigInteger contactId, String firstName, String lastName, String email) {
		this.contactId = contactId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
	}

	public Contacts(BigInteger contactId, Customers customers, String firstName, String lastName, String email,
			String phone) {
		this.contactId = contactId;
		this.customers = customers;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.phone = phone;
	}

	public BigInteger getContactId() {
		return this.contactId;
	}

	public void setContactId(BigInteger contactId) {
		this.contactId = contactId;
	}

	public Customers getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

}
