// default package
// Generated 1 feb 2025, 22:43:07 by Hibernate Tools 6.5.1.Final

import java.math.BigInteger;

/**
 * Countries generated by hbm2java
 */
public class Countries implements java.io.Serializable {

	private String countryId;
	private String countryName;
	private BigInteger regionId;

	public Countries() {
	}

	public Countries(String countryId, String countryName) {
		this.countryId = countryId;
		this.countryName = countryName;
	}

	public Countries(String countryId, String countryName, BigInteger regionId) {
		this.countryId = countryId;
		this.countryName = countryName;
		this.regionId = regionId;
	}

	public String getCountryId() {
		return this.countryId;
	}

	public void setCountryId(String countryId) {
		this.countryId = countryId;
	}

	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	public BigInteger getRegionId() {
		return this.regionId;
	}

	public void setRegionId(BigInteger regionId) {
		this.regionId = regionId;
	}

}
