// default package
// Generated 3 feb 2025, 11:37:11 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Localidad generated by hbm2java
 */
public class Localidad implements java.io.Serializable {

	private int codlocalidad;
	private String nombre;
	private Set personas = new HashSet(0);

	public Localidad() {
	}

	public Localidad(int codlocalidad, String nombre) {
		this.codlocalidad = codlocalidad;
		this.nombre = nombre;
	}

	public Localidad(int codlocalidad, String nombre, Set personas) {
		this.codlocalidad = codlocalidad;
		this.nombre = nombre;
		this.personas = personas;
	}

	public int getCodlocalidad() {
		return this.codlocalidad;
	}

	public void setCodlocalidad(int codlocalidad) {
		this.codlocalidad = codlocalidad;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set personas) {
		this.personas = personas;
	}

}
