// default package
// Generated 3 feb 2025, 11:37:11 by Hibernate Tools 6.5.1.Final

import java.math.BigDecimal;
import java.sql.Date;

/**
 * Multa generated by hbm2java
 */
public class Multa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int codmulta;
	private Persona personaByCodpersonamultada;
	private Persona personaByCodagente;
	private String descripcion;
	private BigDecimal importesancion;
	private Byte puntossancion;
	private Date fechamulta;

	public Multa() {
	}

	public Multa(int codmulta, String descripcion) {
		this.codmulta = codmulta;
		this.descripcion = descripcion;
	}

	public Multa(int codmulta, Persona personaByCodpersonamultada, Persona personaByCodagente, String descripcion,
			BigDecimal importesancion, Byte puntossancion, Date fechamulta) {
		this.codmulta = codmulta;
		this.personaByCodpersonamultada = personaByCodpersonamultada;
		this.personaByCodagente = personaByCodagente;
		this.descripcion = descripcion;
		this.importesancion = importesancion;
		this.puntossancion = puntossancion;
		this.fechamulta = fechamulta;
	}

	public int getCodmulta() {
		return this.codmulta;
	}

	public void setCodmulta(int codmulta) {
		this.codmulta = codmulta;
	}

	public Persona getPersonaByCodpersonamultada() {
		return this.personaByCodpersonamultada;
	}

	public void setPersonaByCodpersonamultada(Persona personaByCodpersonamultada) {
		this.personaByCodpersonamultada = personaByCodpersonamultada;
	}

	public Persona getPersonaByCodagente() {
		return this.personaByCodagente;
	}

	public void setPersonaByCodagente(Persona personaByCodagente) {
		this.personaByCodagente = personaByCodagente;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public BigDecimal getImportesancion() {
		return this.importesancion;
	}

	public void setImportesancion(BigDecimal importesancion) {
		this.importesancion = importesancion;
	}

	public Byte getPuntossancion() {
		return this.puntossancion;
	}

	public void setPuntossancion(Byte puntossancion) {
		this.puntossancion = puntossancion;
	}

	public Date getFechamulta() {
		return this.fechamulta;
	}

	public void setFechamulta(Date fechamulta) {
		this.fechamulta = fechamulta;
	}

}
