// default package
// Generated 3 feb 2025, 11:37:11 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

	private int codpersona;
	private Localidad localidad;
	private String dni;
	private String nombre;
	private String apellidos;
	private Date fechacarnet;
	private byte puntosactuales;
	private Set multasForCodpersonamultada = new HashSet(0);
	private Set multasForCodagente = new HashSet(0);

	public Persona() {
	}

	public Persona(int codpersona, String dni, byte puntosactuales) {
		this.codpersona = codpersona;
		this.dni = dni;
		this.puntosactuales = puntosactuales;
	}

	public Persona(int codpersona, Localidad localidad, String dni, String nombre, String apellidos, Date fechacarnet,
			byte puntosactuales, Set multasForCodpersonamultada, Set multasForCodagente) {
		this.codpersona = codpersona;
		this.localidad = localidad;
		this.dni = dni;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.fechacarnet = fechacarnet;
		this.puntosactuales = puntosactuales;
		this.multasForCodpersonamultada = multasForCodpersonamultada;
		this.multasForCodagente = multasForCodagente;
	}

	public int getCodpersona() {
		return this.codpersona;
	}

	public void setCodpersona(int codpersona) {
		this.codpersona = codpersona;
	}

	public Localidad getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(Localidad localidad) {
		this.localidad = localidad;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Date getFechacarnet() {
		return this.fechacarnet;
	}

	public void setFechacarnet(Date fechacarnet) {
		this.fechacarnet = fechacarnet;
	}

	public byte getPuntosactuales() {
		return this.puntosactuales;
	}

	public void setPuntosactuales(byte puntosactuales) {
		this.puntosactuales = puntosactuales;
	}

	public Set getMultasForCodpersonamultada() {
		return this.multasForCodpersonamultada;
	}

	public void setMultasForCodpersonamultada(Set multasForCodpersonamultada) {
		this.multasForCodpersonamultada = multasForCodpersonamultada;
	}

	public Set getMultasForCodagente() {
		return this.multasForCodagente;
	}

	public void setMultasForCodagente(Set multasForCodagente) {
		this.multasForCodagente = multasForCodagente;
	}

}
