-- Hago un GRANT CREATE TRIGGER TO OT; en jeroAdmin.

CREATE TABLE employee_audits (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER NOT NULL,
    old_email VARCHAR2(255),
    new_email VARCHAR2(255),
    change_date DATE DEFAULT SYSDATE
);


CREATE OR REPLACE TRIGGER trg_audit_email_changes
AFTER UPDATE OF email ON employees
FOR EACH ROW
BEGIN
    -- Registrar los cambios en la tabla employee_audits
    INSERT INTO employee_audits (employee_id, old_email, new_email)
    VALUES (:OLD.employee_id, :OLD.email, :NEW.email);
END;
/

UPDATE employees
SET email = 'nuevo.email@example.com'
WHERE employee_id = 108;


SELECT * FROM employee_audits;

CREATE OR REPLACE TRIGGER trg_no_cantidad_negativa
BEFORE UPDATE OF quantity ON inventories 
FOR EACH ROW
BEGIN
    IF :NEW.quantity < 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'El número no puede ser menor de 0'); -- generar error
    END IF;
END;
/