// default package
// Generated 13 ene 2025, 12:30:21 by Hibernate Tools 6.5.1.Final

import java.math.BigInteger;
import java.sql.Date;

/**
 * EmployeeAudits generated by hbm2java
 */
public class EmployeeAudits implements java.io.Serializable {

	private BigInteger auditId;
	private BigInteger employeeId;
	private String oldEmail;
	private String newEmail;
	private Date changeDate;

	public EmployeeAudits() {
	}

	public EmployeeAudits(BigInteger auditId, BigInteger employeeId) {
		this.auditId = auditId;
		this.employeeId = employeeId;
	}

	public EmployeeAudits(BigInteger auditId, BigInteger employeeId, String oldEmail, String newEmail,
			Date changeDate) {
		this.auditId = auditId;
		this.employeeId = employeeId;
		this.oldEmail = oldEmail;
		this.newEmail = newEmail;
		this.changeDate = changeDate;
	}

	public BigInteger getAuditId() {
		return this.auditId;
	}

	public void setAuditId(BigInteger auditId) {
		this.auditId = auditId;
	}

	public BigInteger getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(BigInteger employeeId) {
		this.employeeId = employeeId;
	}

	public String getOldEmail() {
		return this.oldEmail;
	}

	public void setOldEmail(String oldEmail) {
		this.oldEmail = oldEmail;
	}

	public String getNewEmail() {
		return this.newEmail;
	}

	public void setNewEmail(String newEmail) {
		this.newEmail = newEmail;
	}

	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

}
