// default package
// Generated 13 ene 2025, 12:30:21 by Hibernate Tools 6.5.1.Final

/**
 * InventoriesId generated by hbm2java
 */
public class InventoriesId implements java.io.Serializable {

	private long productId;
	private long warehouseId;

	public InventoriesId() {
	}

	public InventoriesId(long productId, long warehouseId) {
		this.productId = productId;
		this.warehouseId = warehouseId;
	}

	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	public long getWarehouseId() {
		return this.warehouseId;
	}

	public void setWarehouseId(long warehouseId) {
		this.warehouseId = warehouseId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InventoriesId))
			return false;
		InventoriesId castOther = (InventoriesId) other;

		return (this.getProductId() == castOther.getProductId())
				&& (this.getWarehouseId() == castOther.getWarehouseId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getProductId();
		result = 37 * result + (int) this.getWarehouseId();
		return result;
	}

}
