// default package
// Generated 13 ene 2025, 12:30:21 by Hibernate Tools 6.5.1.Final

/**
 * Inventories generated by hbm2java
 */
public class Inventories implements java.io.Serializable {

	private InventoriesId id;
	private Products products;
	private Warehouses warehouses;
	private int quantity;

	public Inventories() {
	}

	public Inventories(InventoriesId id, Products products, Warehouses warehouses, int quantity) {
		this.id = id;
		this.products = products;
		this.warehouses = warehouses;
		this.quantity = quantity;
	}

	public InventoriesId getId() {
		return this.id;
	}

	public void setId(InventoriesId id) {
		this.id = id;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Warehouses getWarehouses() {
		return this.warehouses;
	}

	public void setWarehouses(Warehouses warehouses) {
		this.warehouses = warehouses;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
