// default package
// Generated 13 ene 2025, 12:30:21 by Hibernate Tools 6.5.1.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Locations generated by hbm2java
 */
public class Locations implements java.io.Serializable {

	private BigInteger locationId;
	private Countries countries;
	private String address;
	private String postalCode;
	private String city;
	private String state;
	private Set warehouseses = new HashSet(0);

	public Locations() {
	}

	public Locations(BigInteger locationId, String address) {
		this.locationId = locationId;
		this.address = address;
	}

	public Locations(BigInteger locationId, Countries countries, String address, String postalCode, String city,
			String state, Set warehouseses) {
		this.locationId = locationId;
		this.countries = countries;
		this.address = address;
		this.postalCode = postalCode;
		this.city = city;
		this.state = state;
		this.warehouseses = warehouseses;
	}

	public BigInteger getLocationId() {
		return this.locationId;
	}

	public void setLocationId(BigInteger locationId) {
		this.locationId = locationId;
	}

	public Countries getCountries() {
		return this.countries;
	}

	public void setCountries(Countries countries) {
		this.countries = countries;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Set getWarehouseses() {
		return this.warehouseses;
	}

	public void setWarehouseses(Set warehouseses) {
		this.warehouseses = warehouseses;
	}

}
