// default package
// Generated 13 ene 2025, 12:30:21 by Hibernate Tools 6.5.1.Final

/**
 * OrderItemsId generated by hbm2java
 */
public class OrderItemsId implements java.io.Serializable {

	private long itemId;
	private long orderId;

	public OrderItemsId() {
	}

	public OrderItemsId(long itemId, long orderId) {
		this.itemId = itemId;
		this.orderId = orderId;
	}

	public long getItemId() {
		return this.itemId;
	}

	public void setItemId(long itemId) {
		this.itemId = itemId;
	}

	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderItemsId))
			return false;
		OrderItemsId castOther = (OrderItemsId) other;

		return (this.getItemId() == castOther.getItemId()) && (this.getOrderId() == castOther.getOrderId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getItemId();
		result = 37 * result + (int) this.getOrderId();
		return result;
	}

}
