// default package
// Generated 13 ene 2025, 12:30:21 by Hibernate Tools 6.5.1.Final

import java.math.BigDecimal;

/**
 * OrderItems generated by hbm2java
 */
public class OrderItems implements java.io.Serializable {

	private OrderItemsId id;
	private Products products;
	private Orders orders;
	private BigDecimal quantity;
	private BigDecimal unitPrice;

	public OrderItems() {
	}

	public OrderItems(OrderItemsId id, Products products, Orders orders, BigDecimal quantity, BigDecimal unitPrice) {
		this.id = id;
		this.products = products;
		this.orders = orders;
		this.quantity = quantity;
		this.unitPrice = unitPrice;
	}

	public OrderItemsId getId() {
		return this.id;
	}

	public void setId(OrderItemsId id) {
		this.id = id;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

}
