// default package
// Generated 13 ene 2025, 12:30:21 by Hibernate Tools 6.5.1.Final

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private BigInteger productId;
	private ProductCategories productCategories;
	private String productName;
	private String description;
	private BigDecimal standardCost;
	private BigDecimal listPrice;
	private Set inventorieses = new HashSet(0);
	private Set orderItemses = new HashSet(0);

	public Products() {
	}

	public Products(BigInteger productId, ProductCategories productCategories, String productName) {
		this.productId = productId;
		this.productCategories = productCategories;
		this.productName = productName;
	}

	public Products(BigInteger productId, ProductCategories productCategories, String productName, String description,
			BigDecimal standardCost, BigDecimal listPrice, Set inventorieses, Set orderItemses) {
		this.productId = productId;
		this.productCategories = productCategories;
		this.productName = productName;
		this.description = description;
		this.standardCost = standardCost;
		this.listPrice = listPrice;
		this.inventorieses = inventorieses;
		this.orderItemses = orderItemses;
	}

	public BigInteger getProductId() {
		return this.productId;
	}

	public void setProductId(BigInteger productId) {
		this.productId = productId;
	}

	public ProductCategories getProductCategories() {
		return this.productCategories;
	}

	public void setProductCategories(ProductCategories productCategories) {
		this.productCategories = productCategories;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public BigDecimal getStandardCost() {
		return this.standardCost;
	}

	public void setStandardCost(BigDecimal standardCost) {
		this.standardCost = standardCost;
	}

	public BigDecimal getListPrice() {
		return this.listPrice;
	}

	public void setListPrice(BigDecimal listPrice) {
		this.listPrice = listPrice;
	}

	public Set getInventorieses() {
		return this.inventorieses;
	}

	public void setInventorieses(Set inventorieses) {
		this.inventorieses = inventorieses;
	}

	public Set getOrderItemses() {
		return this.orderItemses;
	}

	public void setOrderItemses(Set orderItemses) {
		this.orderItemses = orderItemses;
	}

}
