// default package
// Generated 13 ene 2025, 12:30:21 by Hibernate Tools 6.5.1.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductCategories generated by hbm2java
 */
public class ProductCategories implements java.io.Serializable {

	private BigInteger categoryId;
	private String categoryName;
	private Set productses = new HashSet(0);

	public ProductCategories() {
	}

	public ProductCategories(BigInteger categoryId, String categoryName) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
	}

	public ProductCategories(BigInteger categoryId, String categoryName, Set productses) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.productses = productses;
	}

	public BigInteger getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(BigInteger categoryId) {
		this.categoryId = categoryId;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public Set getProductses() {
		return this.productses;
	}

	public void setProductses(Set productses) {
		this.productses = productses;
	}

}
