// default package
// Generated 13 ene 2025, 12:30:21 by Hibernate Tools 6.5.1.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Regions generated by hbm2java
 */
public class Regions implements java.io.Serializable {

	private BigInteger regionId;
	private String regionName;
	private Set countrieses = new HashSet(0);

	public Regions() {
	}

	public Regions(BigInteger regionId, String regionName) {
		this.regionId = regionId;
		this.regionName = regionName;
	}

	public Regions(BigInteger regionId, String regionName, Set countrieses) {
		this.regionId = regionId;
		this.regionName = regionName;
		this.countrieses = countrieses;
	}

	public BigInteger getRegionId() {
		return this.regionId;
	}

	public void setRegionId(BigInteger regionId) {
		this.regionId = regionId;
	}

	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	public Set getCountrieses() {
		return this.countrieses;
	}

	public void setCountrieses(Set countrieses) {
		this.countrieses = countrieses;
	}

}
