// default package
// Generated 13 ene 2025, 12:30:21 by Hibernate Tools 6.5.1.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Warehouses generated by hbm2java
 */
public class Warehouses implements java.io.Serializable {

	private BigInteger warehouseId;
	private Locations locations;
	private String warehouseName;
	private Set inventorieses = new HashSet(0);

	public Warehouses() {
	}

	public Warehouses(BigInteger warehouseId) {
		this.warehouseId = warehouseId;
	}

	public Warehouses(BigInteger warehouseId, Locations locations, String warehouseName, Set inventorieses) {
		this.warehouseId = warehouseId;
		this.locations = locations;
		this.warehouseName = warehouseName;
		this.inventorieses = inventorieses;
	}

	public BigInteger getWarehouseId() {
		return this.warehouseId;
	}

	public void setWarehouseId(BigInteger warehouseId) {
		this.warehouseId = warehouseId;
	}

	public Locations getLocations() {
		return this.locations;
	}

	public void setLocations(Locations locations) {
		this.locations = locations;
	}

	public String getWarehouseName() {
		return this.warehouseName;
	}

	public void setWarehouseName(String warehouseName) {
		this.warehouseName = warehouseName;
	}

	public Set getInventorieses() {
		return this.inventorieses;
	}

	public void setInventorieses(Set inventorieses) {
		this.inventorieses = inventorieses;
	}

}
